### PR TITLE
Adopt ProcessCronQueueObserver to Magento 2.3.5

### PR DESCRIPTION
**Pull request by flancer64**
Hello, guys.

I suppose we should have compatibility for the freshest version of Magento only. So, I've removed files:
* Observer/ProcessCronQueueObserver_2_1.inc
* Observer/ProcessCronQueueObserverDefault.inc

and have moved code from `ProcessCronQueueObserverDefault.inc` to `\KiwiCommerce\CronScheduler\Observer\ProcessCronQueueObserver`.

If somebody has old versions of Magento, they can use old versions of this module (for Mage < v2.3.5 ):
```
$ composer require kiwicommerce/module-cron-scheduler:1.0.6
```

### CODE REVIEW

**Comment by thampe** [comment]
hi,

is there any news when this will be resolved?

**Comment by flancer64** [comment]
@thampe , you can use patched version from my repo until this issue will not be resolved:

```
$ composer config repositories.magento2-cron-scheduler vcs https://github.com/flancer64/magento2-cron-scheduler/
$ composer require kiwicommerce/module-cron-scheduler
```

**Comment by thampe** [comment]
Thanks :). I will use this until this pr is merged.

**Comment by GTWarehouse** [comment]
How do I update the extension if I have it installed via upload in the app\code folder?

**Comment by kiwi-commerce** [comment]
Hello @flancer64, Thanks for your PR.

We have performed this change on the following commit.
- 4b617d13ffc7666698ee6539f75d686e5dfd33f7

We have released the new version v1.0.8 and closing this PR.

Thank you.

**Pull request closed without merging**
